[project]
name = "umbridge-workshop-2024"
version = "0.1.0"
description = "Repository for the 2024 Umbridge Workshop"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "laser-measles",
]

[tool.uv.sources]
laser-measles = { git = "https://github.com/krosenfeld-IDM/laser-measles.git", rev = "umbridge-workshop" }
